configuration/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import pretty_auth.urls as pretty_auth
import pretty_profile.urls as pretty_profile
import pretty_search.urls as pretty_search
import pretty_update_status.urls as pretty_update_status
import pretty_history.urls as pretty_history

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pretty_auth/', include(pretty_auth, namespace='pretty-auth')),
    url(r'^pretty_profile/', include(pretty_profile, namespace='pretty-profile')),
    url(r'^pretty_search/', include(pretty_search, namespace='pretty-search')),
    url(r'^pretty_update_status/', include(pretty_update_status, namespace='pretty-update-status')),
    url(r'^pretty_history/', include(pretty_history, namespace= 'pretty-history')),
    url(r'^$', RedirectView.as_view(url='/pretty_auth/', permanent=True), name='index')
]

pretty_auth/urls.py
from django.conf.urls import url
from .views import *
from .custom_auth import auth_login, auth_logout

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login/', login, name='login'),
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

]

pretty_auth/models.py
from django.db import models

# Create your models here.
class User(models.Model):
	name = models.CharField(max_length=100,null=True)
	npm = models.CharField(max_length=20)
	url_linkedin = models.URLField(null=True)
	photo = models.URLField(null=True)
	email = models.EmailField(max_length=200,null=True)
	show_score = models.BooleanField(default=True)
	headline = models.CharField(max_length=300,null=True)
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

class Expertise(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	java = 'java'
	c = 'c'
	python = 'python'
	PPW = 'ppw'
	expertise_choices = (
		(java, 'Java'),
		(c, 'C#'),
		(python, 'Python'),
		(PPW, 'PPW'),
	)
	expertise = models.CharField(
		max_length=2,
		choices=expertise_choices,
		)
	beginner = 'beginner'
	intermediate = 'intermediate'
	advanced = 'advanced'
	expert = 'expert'
	legend = 'legend'
	level_choices = (
		(beginner, 'Beginner'),
		(intermediate, 'Intermediate'),
		(advanced, 'Advanced'),
		(expert, 'Expert'),
		(legend, 'Legend'),
		)
	level = models.CharField(
		max_length=2,
		choices=level_choices,
		)
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)


class Status(models.Model):
	username = models.CharField(max_length=100,null=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	message = models.CharField(max_length=128)
	created_date = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

pretty_auth/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages

response = {}

def index(request): # pragma: no cover
    response['author'] = "Team PrettyPrettyWebsite"
    html = "pretty_auth/auth.html"
    response['is_login'] = False
    return render(request, html, response)

def login(request): # pragma: no cover
    print ("#==> masuk login")
    if 'user_login' in request.session:
        response['is_login'] = True
        return HttpResponseRedirect(reverse('pretty-profile:index'))
    else:
        response['is_login'] = False
        html = 'pretty_auth/session/login.html'
        return render(request, html, response)

def authenticate(request):
	return ('user_login' in request.session.keys())

pretty_auth/templates/pretty_auth/partials/footer.html
<!-- templates/lab_9/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->

<style>

.centered{
  text-align: center;
}

</style>

<p class="centered">© Made with Love by {{author}}</p>

pretty_auth/templates/pretty_auth/partials/header.html
<!-- templates/lab_9/partials/header.html -->
<nav class="navbar navbar-default navbar-static-top" style="background-color:#10293A">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" style="color: blue">PrettyPrettyWebsite2</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
          <li><a href="/pretty_profile" style="color: blue">{{userName}}</a></li>

          {% if is_login %}
            <li><a href="{% url 'pretty-auth:auth_logout' %}" class="pull-right" onclick="return confirm('Logging out?')" style="color:blue">
              Logout </a></li>
          {% else %}
            <li><a href="{% url 'pretty-auth:login' %}" class="pull-right" style="color:blue">Login</a></li>
          {% endif %}
      </ul>
    </div>
  </div>
</nav>