configuration/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import pretty_auth.urls as pretty_auth
import pretty_profile.urls as pretty_profile
import pretty_search.urls as pretty_search
import pretty_update_status.urls as pretty_update_status
import pretty_history.urls as pretty_history

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pretty_auth/', include(pretty_auth, namespace='pretty-auth')),
    url(r'^pretty_profile/', include(pretty_profile, namespace='pretty-profile')),
    url(r'^pretty_search/', include(pretty_search, namespace='pretty-search')),
    url(r'^pretty_update_status/', include(pretty_update_status, namespace='pretty-update-status')),
    url(r'^pretty_history/', include(pretty_history, namespace= 'pretty-history')),
    url(r'^$', RedirectView.as_view(url='/pretty_auth/', permanent=True), name='index')
]

pretty_auth/urls.py
from django.conf.urls import url
from .views import *
from .custom_auth import auth_login, auth_logout

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login/', login, name='login'),
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

]

pretty_profile/urls.py
from django.conf.urls import url
from .views import index, edit_profile, update_profile, edit_profile_local, delete_skill

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^edit/', edit_profile, name='edit-profile'),
    url(r'^update-profile/$', update_profile, name='update-profile'),
    url(r'^edit-profile-local/$', edit_profile_local, name='edit-profile-local'),
    url(r'^delete-skill/(?P<skillname>[a-zA-Z]+)$', delete_skill, name='delete-skill')

]

pretty_profile/models.py
from django.db import models

# Create your models here.
class Profile(models.Model):
    name = models.CharField(max_length=100)
    birthday = models.DateField()
    gender = models.CharField(max_length=10)
    expertise = models.CharField(max_length=100)
    description = models.TextField()
    email = models.EmailField()
    created_at = models.DateTimeField(auto_now_add = True)

pretty_profile/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import messages
from django.shortcuts import render
from django.http import *
from django.http import QueryDict
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from pretty_auth.views import authenticate
from .utils import *
from pretty_auth.models import User, Status, Expertise
from pretty_search.models import Friend
from pretty_search import views
from django.urls import reverse
from pretty_update_status.forms import Status_Form
from pretty_history.api_riwayat import get_riwayat

response = {}
def index(request): # pragma: no cover
    if not authenticate(request):
        return HttpResponseRedirect(reverse('pretty-auth:index'))
    else:
        response['is_login'] = True
        kode_identitas = get_data_user(request, 'kode_identitas')
        user_exist = check_user_in_database(request, kode_identitas)
        if (user_exist):
            user = User.objects.get(npm = kode_identitas)
        else:
            user = create_new_user(request)
        response['user'] = user
        if Status.objects.filter(user=user).count() > 0:
            latest_status = Status.objects.filter(user=user).latest('created_date')
            response['latest_status'] = latest_status
            status_count = Status.objects.filter(user=user).count()
            response['status_count'] = status_count
        else:
            response['latest_status'] = "You haven't post anything"
            response['status_count'] = 0
        html = 'pretty_auth/session/home.html'
        expertise = Expertise.objects.filter(user=user)
        response['expertise'] = expertise
        response['menuSelected'] = 'profile'
        response['author'] = "Team PrettyPrettyWebsite"

        if user.name == None or "None":
            response['userName'] = get_data_user(request, 'user_login')
            messages.success(request, "Please update your profile")
        else:
            response['userName'] = user.name

        #--------pretty_update_status-------#
        status = Status.objects.filter(user=user)
        response['status'] = status
        response['status_form'] = Status_Form

        #-----------pretty_search-----------#
        friend_list = Friend.objects.all()
        response['friend_list'] = friend_list

        #-----------pretty_history-----------#
        response['riwayats'] = get_riwayat()

        return render(request, html, response)

def edit_profile(request): # pragma: no cover
    if not authenticate(request):
        return HttpResponseRedirect(reverse('pretty-auth:index'))
    else:
        kode_identitas = get_data_user(request, 'kode_identitas')
        user = User.objects.get(npm = kode_identitas)
        if Status.objects.filter(user=user).count() > 0:
            latest_status = Status.objects.filter(user=user).latest('created_date')
            response['latest_status'] = latest_status
            status_count = Status.objects.filter(user=user).count()
            response['status_count'] = status_count
        response['user'] = user
        skill = Expertise.objects.filter(user=user)
        response['skill'] = skill
        response['connected'] = check_user_connected_linkedin(request, kode_identitas)
        html = 'pretty_profile/edit_profile.html'
        return render(request, html, response)

@csrf_exempt
def update_profile(request): # pragma: no cover
    if request.method == 'POST':
        kode_identitas = get_data_user(request, 'kode_identitas')
        user = User.objects.get(npm = kode_identitas)
        fullname = request.POST['full_name']
        url_linkedin = request.POST['url_linkedin']
        picture_url = request.POST['picture_url']
        email = request.POST['email']
        headline = request.POST['headline']
        user.name = fullname
        user.url_linkedin = url_linkedin
        user.photo = picture_url
        user.email = email
        user.headline = headline
        user.save()
        return HttpResponseRedirect(reverse('pretty-profile:edit-profile'))

@csrf_exempt
def edit_profile_local(request): # pragma: no cover
    if request.method == 'POST':
        request.POST = request.POST.copy()
        show = request.POST['show_score']
        expertise = request.POST.getlist('skill')
        level = request.POST.getlist('level')
        kode_identitas = get_data_user(request, 'kode_identitas')
        user = User.objects.get(npm = kode_identitas)
        counter = 0;
        for a in expertise:
            if (Expertise.objects.filter(user=user,expertise=a)):
                expertiseObj = Expertise.objects.get(user=user,expertise=a)
                expertiseObj.expertise = a
                expertiseObj.level = level[counter]
            else:
                expertiseObj = Expertise.objects.create(user=user, expertise=a,level=level[counter])
            expertiseObj.save()
            counter += 1
        user.show_score = show
        user.save()
    return HttpResponseRedirect(reverse('pretty-profile:edit-profile'))

def delete_skill(request,skillname):# pragma: no cover
    print('=====>delete')
    if request.method == 'GET':
        kode_identitas = get_data_user(request, 'kode_identitas')
        user = User.objects.get(npm = kode_identitas)
        Expertise.objects.get(user=user,expertise = skillname).delete()
        return HttpResponseRedirect(reverse('pretty-profile:edit-profile-local'))

pretty_profile/templates/pretty_profile/edit_profile.html
{% extends "pretty_auth/layout/base.html" %}
{% block content %}
{% load staticfiles %}
{% load static %}

<style>
.circle-image {
  border: 2px solid #ccc;
  border-radius:  50%;
  height:200px;
  width:200px;
}
</style>

<div style="overflow: hidden">
  <form action="{% url 'pretty-profile:edit-profile-local' %}" method="POST">
    <div class="profile" style="float:center">
      <img src="/static/images/giphy.gif" class="circle-image" />
      <br>
      <br>
      <strong> NPM: {{user.npm}} </strong>
      <br>
      <br>
    </div>
    <div style="float:center; position:pull-right">
      <input type="submit" class="editProfileButton btn btn-info" style="border:1px solid blue">
      <a onclick="logOutFromLinkedin();" class="editProfileButton btn btn-info" style="border:1px solid blue">Logout</a>
      <br>
      <br>
    </div>

    <div>
      {% csrf_token %}
      <p><b>Show Score: </b>
        Yes <input type="radio" name="show_score" value="True" {% if user.show_score == True %} checked{% endif %}>
        No <input type="radio" name="show_score" value="False" {% if user.show_score == False %} checked{% endif %}>
      </p>
    </div>
    <br>

    <div>
      {% if connected %}
      <div class="loginWithLinkedIn" style="background-color:#87C8F5; border:white" id="boxed">
      </div>
      {% else %}
      <script type="in/Login"></script>
      {% endif %}
      <br>
      <br>
    </div>
    <div class="appendSkill">
      {% if skill %}
      {% for s in skill %}
      <div class="skillChooserContainer">
        <div style="float:left; padding-left:470px">
          <h2>Expertise</h2>
          <select name="skill">
            <option value="java" {% if s.expertise == 'java' %} selected{% endif %}>Java</option>
            <option value="python" {% if s.expertise == 'python' %} selected{% endif %}>Python</option>
            <option value="c" {% if s.expertise == 'c' %} selected{% endif %}>C#</option>
            <option value="ppw" {% if s.expertise == 'ppw' %} selected{% endif %}>PPW</option>
          </select>
        </div>
        <div style="float:right; padding-right:470px">
          <h2>Level</h2>
          <select name="level">
            <option value="beginner" {% if s.level == 'beginner' %} selected{% endif %}>Beginner</option>
            <option value="intermediate" {% if s.level == 'intermediate' %} selected{% endif %}>Intermediate</option>
            <option value="expert" {% if s.level == 'expert' %} selected{% endif %}>Expert</option>
            <option value="legend" {% if s.level == 'legend' %} selected{% endif %}>Legend</option>
          </select>
        </div>

        <div style="text-align:center">
          <a href="{% url 'pretty-profile:delete-skill' s.expertise %}"><div style="font-family: 'Open Sans';color:red;border: 1px solid white;">Delete</div></a>
        </div>

      </div>
      {% endfor %}
      {% endif %}
      <div>
        <br>
        <button class="btn btn-info" onclick="addSkill()" style="border:2px solid blue">Add Skill</button>
        <button class="btn btn-info" onclick="cancel()" style="border:2px solid blue">Cancel</button>
      </div>
    </div>

  </form>
</div>

<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous">
</script>

<script type="text/javascript" src="//platform.linkedin.com/in.js">
  api_key: 81uy3ffey1q8uk
  onLoad: onLinkedInLoad
  authorize: true
  lang:
</script>

<script type="text/javascript">
  // Setup an event listener to make an API call once auth is complete
  function onLinkedInLoad() {
    IN.Event.on(IN, "auth", getProfileData);
  }

  // Handle the successful return from the API call
  function onSuccess(data) {
    console.log(data);
    const fullName = data.firstName+" "+data.lastName;
    const profileUrl = data.publicProfileUrl;
    html = "<i><strong style='font-size:18px; color:blue'> LinkedIn Profile </strong></i>" +
           "<strong style='font-size:16px'> <center> " +
           "Name: " + data.firstName+" "+data.lastName + "<br>" +
           "Email: " + data.emailAddress + "<br>" +
           "Location: " + data.location.name + "<br>" +
           "Headline: " + data.headline + "<br>" +
           "LinkedIn: <a href='" + data.publicProfileUrl + "'>" + data.publicProfileUrl + "</a><br>" +
           "</center> </strong>";

    $('.loginWithLinkedIn').append(html)
    updateProfile(data);
  }

  function updateProfile(data) {
<<<<<<< HEAD
    var show_score = document.getElementById
=======
<<<<<<< HEAD
=======
    var show_score = document.getElementById
>>>>>>> bbeb0c05632a44e12a2c7508b84478fad6837a5c
>>>>>>> search
    $.ajax({
      method : 'POST',
      url : "{% url 'pretty-profile:update-profile' %}",
      data : {
        'full_name' : data.firstName+" "+data.lastName,
        'url_linkedin': data.publicProfileUrl,
        'picture_url': data.pictureUrl,
        'email': data.emailAddress,
        'headline': data.headline,
      },
      dataType : 'json',
      success : function(response) {
        window.location = '/pretty-profile';
      },
      error : function(error) {
        console.log(error);
      }
    });
  }

  // Handle an error response from the API call
  function onError(error) {
    console.log(error);
  }

  // Use the API call wrapper to request the member's basic profile data
  function getProfileData() {
    IN.API.Raw("/people/~:(first-name,last-name,headline,email-address,picture-url,public-profile-url,location)").result(onSuccess).error(onError);
  }

  function logOutFromLinkedin() {
    IN.User.logout(logOut);
    $.ajax({
      method : 'POST',
      url : "{% url 'pretty-profile:update-profile' %}",
      data : {
        'full_name' : "None",
        'url_linkedin': "None",
        'picture_url': "/static/images/giphy.gif",
        'email': "None",
        'headline': "None",
      },
      dataType : 'json',
      success : function(response) {
        window.location = '/pretty-profile';
        window.location.reload();
      },
      error : function(error) {
        console.log(error);
      }
    });
    $('.loginWithLinkedIn').empty();
    return true;
  }

  function logOut() {
    $.ajax({
      method : 'POST',
      url : "{% url 'pretty-auth:auth_logout' %}",
      success : function(response) {
        window.location.reload();
      },
      error : function(error) {
        console.log(error);
      }
    });
  }

  function addSkill() {
    html = '<div class="skillChooserContainerPick"><div style="float:left; padding-left:470px"><h3>Expertise</h3><select name="skill"><option value="java">Java</option><option value="python">Python</option><option value="c">C#</option><option value="ppw">PPW</option></select></div><div style="float:right; padding-right:470px"><h3>Level</h3><select name="level"><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="expert">Expert</option><option value="legend">Legend</option></select></div></div></div>'
    $('.appendSkill').append(html);
    event.preventDefault()
  }

  function cancel() {
    $('.skillChooserContainerPick').last().remove();
    event.preventDefault()
  }

</script>
{% endblock %}

pretty_profile/templates/pretty_profile/profile.html
{% block content %}

<style>
.expert {
  border: 2px solid #106AA8;
  padding: 0.4rem;
  margin: 0.2 rem;
  border-radius: 1rem;
  font-size: 0.8rem;
  color: gray;
}

#legend{
  color: red;
}
#expert{
  color: orange;
}
#advanced{
  color: yellow;
}
#intermediate{
  color:green;
}
#beginner{
  color: magenta;
}

</style>

<center class="profile" style="font-size:18px">
  <p><b>Name: </b>{{ user.name }}</p>
  <p><b>NPM: </b>{{ user.npm }}</p>
  <p><b>Expertise: </b>
    {% if expertise %}
      {% for ii in expertise %}
        <span class="expert" style="font-size:14px">
          <strong id="{{ ii.level }}"> {{ ii.expertise }} </strong>
        </span>
        &nbsp;
      {% endfor %}
    {% else %}
      None
    {% endif %}
  </p>
  <p><b>Email: </b>{{ user.email }}</p>
  <p><b>LinkedIn Profile: </b>{{ user.url_linkedin}}</p>
</center>

{% endblock %}