configuration/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import pretty_auth.urls as pretty_auth
import pretty_profile.urls as pretty_profile
import pretty_search.urls as pretty_search
import pretty_update_status.urls as pretty_update_status
import pretty_history.urls as pretty_history

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pretty_auth/', include(pretty_auth, namespace='pretty-auth')),
    url(r'^pretty_profile/', include(pretty_profile, namespace='pretty-profile')),
    url(r'^pretty_search/', include(pretty_search, namespace='pretty-search')),
    url(r'^pretty_update_status/', include(pretty_update_status, namespace='pretty-update-status')),
    url(r'^pretty_history/', include(pretty_history, namespace= 'pretty-history')),
    url(r'^$', RedirectView.as_view(url='/pretty_auth/', permanent=True), name='index')
]

pretty_auth/urls.py
from django.conf.urls import url
from .views import *
from .custom_auth import auth_login, auth_logout

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login/', login, name='login'),
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

]

pretty_profile/urls.py
from django.conf.urls import url
from .views import index, edit_profile, update_profile, edit_profile_local, delete_skill

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^edit/', edit_profile, name='edit-profile'),
    url(r'^update-profile/$', update_profile, name='update-profile'),
    url(r'^edit-profile-local/$', edit_profile_local, name='edit-profile-local'),
    url(r'^delete-skill/(?P<skillname>[a-zA-Z]+)$', delete_skill, name='delete-skill')

]

pretty_auth/models.py
from django.db import models

# Create your models here.
class User(models.Model):
	name = models.CharField(max_length=100,null=True)
	npm = models.CharField(max_length=20)
	url_linkedin = models.URLField(null=True)
	photo = models.URLField(null=True)
	email = models.EmailField(max_length=200,null=True)
	show_score = models.BooleanField(default=True)
	headline = models.CharField(max_length=300,null=True)
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

class Expertise(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	java = 'java'
	c = 'c'
	python = 'python'
	PPW = 'ppw'
	expertise_choices = (
		(java, 'Java'),
		(c, 'C#'),
		(python, 'Python'),
		(PPW, 'PPW'),
	)
	expertise = models.CharField(
		max_length=2,
		choices=expertise_choices,
		)
	beginner = 'beginner'
	intermediate = 'intermediate'
	advanced = 'advanced'
	expert = 'expert'
	legend = 'legend'
	level_choices = (
		(beginner, 'Beginner'),
		(intermediate, 'Intermediate'),
		(advanced, 'Advanced'),
		(expert, 'Expert'),
		(legend, 'Legend'),
		)
	level = models.CharField(
		max_length=2,
		choices=level_choices,
		)
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)


class Status(models.Model):
	username = models.CharField(max_length=100,null=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	message = models.CharField(max_length=128)
	created_date = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

pretty_auth/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages

response = {}

def index(request): # pragma: no cover
    response['author'] = "Team PrettyPrettyWebsite"
    html = "pretty_auth/auth.html"
    response['is_login'] = False
    return render(request, html, response)

def login(request): # pragma: no cover
    print ("#==> masuk login")
    if 'user_login' in request.session:
        response['is_login'] = True
        return HttpResponseRedirect(reverse('pretty-profile:index'))
    else:
        response['is_login'] = False
        html = 'pretty_auth/session/login.html'
        return render(request, html, response)

def authenticate(request):
	return ('user_login' in request.session.keys())

pretty_auth/templates/pretty_auth/session/home.html
{% extends "pretty_auth/layout/base.html" %}
{% block content %}
<style>
.circle-image {
  border: 2px solid #ccc;
  border-radius:  50%;
  height:200px;
  width:200px;
}

.zero {
  display: flex;
}

.one {
  flex: 50%;
}

.two {
  flex: 50%;
}
}

</style>

<h1> Welcome, {{userName}}! </h1>
<br>
<div class="zero">
  <br>
  <div class="one">
    {% if user.photo %}
      <img src="{{ user.photo }}" class="circle-image"/>
    {% else %}
      <img src="../static/images/giphy.gif" class="circle-image" />
    {% endif %}
    <a href="{% url 'pretty-profile:edit-profile' %}" style="color:blue" class="btn btn-info"> <strong style="font-size:18px"> Edit Profile </strong> </a>
  </div>
  <br>
  <br>

  <div class="two">
    <br>
    <b style="font-size:20px; font-style:italic"> Status Count </b>
    <p> {{status_count}} </p>
    <b style="font-size:20px; font-style:italic"> Latest Status </b>
    {% if status_count > 0 %}
    <p> {{latest_status.message|linebreaks}} </p>
    <p> {{latest_status.created_date}} </p>
    {% else %}
    <p> {{latest_status}} </p>
    {% endif %}
    <br>
  </div>
</div>

<div style="float:left">
  <br>
  <br>
  <ul class="nav nav-tabs nav-justified" role="tablist">
      <li role="presentation" class="active">
          <a href="#profile" aria-controls="home" role="tab" data-toggle="tab"> <strong style="color:black"> Profile </strong> </a>
      </li>
      <li role="presentation">
          <a href="#history" aria-controls="settings" role="tab" data-toggle="tab"> <strong style="color:black"> History </strong> </a>
      </li>
      <li role="presentation">
          <a href="#status" aria-controls="settings" role="tab" data-toggle="tab"> <strong style="color:black"> Status </strong> </a>
      </li>
      <li role="presentation">
          <a href="#friend" aria-controls="settings" role="tab" data-toggle="tab"> <strong style="color:black"> Friend </strong> </a>
      </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content" style="background-color:#87C8F5; border:white" id="boxed">
      <br>
      <div role="tabpanel" class="tab-pane fade in active" id="profile">
            {% include 'pretty_profile/profile.html' %}
      </div>
      <div role="tabpanel" class="tab-pane fade" id="history">
          <!-- TODO -->
          {% include 'pretty_history/history.html' %}
        </div>
      <div role="tabpanel" class="tab-pane fade" id="status">
          <!-- TODO -->
		        {% include 'pretty_update_status.html' %}
      </div>
      <div role="tabpanel" class="tab-pane fade" id="friend">
          <!-- TODO -->
            {% include 'pretty_search/search.html' %}
      </div>
      <br>
  </div>
</div>

{% endblock %}

pretty_auth/templates/pretty_auth/session/login.html
{% extends "pretty_auth/layout/base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> Login Page </h1>
                <p class="text-info"> Use <b> SSO account </b> to login </p>
            </div>
            <form action="{% url 'pretty-auth:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}